server:
  http_listen_port: 3200

distributor:
  rate_limit_enabled: false

ingester:
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

querier:
  frontend_worker:
    frontend_address: localhost:3200
